# Generated by Django 4.1.2 on 2022-11-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_category_alter_book_options_alter_book_cover_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterIndexTogether(
            name='book',
            index_together=set(),
        ),
    ]
