# Generated by Django 4.1.2 on 2022-11-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_category_options_alter_book_index_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
