# Generated by Django 4.1.2 on 2022-11-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
