# Generated by Django 4.1.2 on 2022-11-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('boutique', '0003_alter_boutique_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='books.book'),
        ),
    ]
