# Generated by Django 4.1.2 on 2022-11-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_boutique_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boutique',
            name='books',
        ),
    ]
